import Link from 'next/link'
import { ArrowUpRight, ChevronRight, CircleCheck, Clock3, Database, Filter, MoreHorizontal, Play, ShieldCheck, TriangleAlert, Zap } from 'lucide-react'
import { AppShell, SectionHeading, StatCard } from '@/components/app-shell'

const batches = [['BATCH-24.08.17', 'Industrial MRO master', '18,420', '99.2%', 'Completed'], ['BATCH-24.08.16', 'Electrical components', '12,860', '96.8%', 'Completed'], ['BATCH-24.08.15', 'Facilities & safety', '9,340', '91.4%', 'Review']]
export default function Page() { return <AppShell title="Pipeline overview"><div className="mx-auto max-w-[1500px]">
  <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.18em] text-cyan-300"><span className="status-dot cyan" />Live pipeline</p><h2 className="text-balance text-3xl font-semibold tracking-tight md:text-4xl">Catalog intelligence, <span className="text-cyan-300">in motion.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Monitor enrichment throughput, review exceptions, and keep your enterprise catalog moving from raw data to trusted records.</p></div><div className="flex gap-2"><Link href="/workbench" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground hover:opacity-90"><Play className="size-4" />Open workbench</Link><button className="rounded-md border border-border px-4 py-2.5 text-sm text-muted-foreground hover:bg-accent">Export report</button></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Records processed" value="40,620" detail="+18.4% vs previous batch" tone="cyan" /><StatCard label="Auto-approved" value="96.8%" detail="Target threshold 94.0%" tone="emerald" /><StatCard label="Human review" value="14" detail="Items require attention" tone="amber" /><StatCard label="Avg. confidence" value="93.4" detail="+2.1 points this run" tone="cyan" /></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]">
    <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Throughput telemetry</p><h3 className="mt-1 font-semibold">Processing velocity</h3></div><span className="flex items-center gap-2 text-xs text-emerald-300"><span className="status-dot emerald" />12.4k records / hour</span></div><div className="p-5"><div className="flex h-56 items-end gap-2 border-b border-border pb-0">{[35,48,42,65,55,72,68,87,78,94,82,100,92,96,88,100,96,100].map((height, index) => <div key={index} className="group flex h-full flex-1 flex-col justify-end gap-2"><div className="rounded-t-sm bg-cyan-300/70 transition-colors group-hover:bg-cyan-200" style={{ height: `${height * 2.1}px` }} /></div>)}</div><div className="mt-4 flex justify-between font-mono text-[10px] text-muted-foreground"><span>08:00</span><span>12:00</span><span>16:00</span><span>Now</span></div></div></section>
    <section className="panel p-5"><SectionHeading eyebrow="Confidence distribution" title="Model certainty" description="Current batch across 40,620 records" /><div className="flex items-center justify-center py-4"><div className="relative flex size-48 items-center justify-center rounded-full" style={{background:'conic-gradient(#67e8f9 0 68%, #34d399 68% 91%, #fbbf24 91% 97%, #fb7185 97% 100%)'}}><div className="flex size-32 flex-col items-center justify-center rounded-full bg-card"><span className="font-mono text-3xl">93.4</span><span className="text-xs text-muted-foreground">avg score</span></div></div></div><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="mr-2 inline-block size-2 rounded-full bg-cyan-300" />High confidence <b className="float-right">68%</b></div><div><span className="mr-2 inline-block size-2 rounded-full bg-emerald-400" />Approved <b className="float-right">23%</b></div><div><span className="mr-2 inline-block size-2 rounded-full bg-amber-300" />Review <b className="float-right">6%</b></div><div><span className="mr-2 inline-block size-2 rounded-full bg-rose-400" />Exception <b className="float-right">3%</b></div></div></section>
  </div>
  <section className="panel mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Batch history</p><h3 className="mt-1 font-semibold">Recent enrichment runs</h3></div><button className="flex items-center gap-2 rounded-md border border-border px-3 py-2 text-xs text-muted-foreground hover:bg-accent"><Filter className="size-3.5" />Filter view</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-accent/30 font-mono text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3">Batch</th><th className="px-5 py-3">Source</th><th className="px-5 py-3">Records</th><th className="px-5 py-3">Confidence</th><th className="px-5 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody>{batches.map(([batch, source, records, confidence, status]) => <tr key={batch} className="border-t border-border hover:bg-accent/20"><td className="px-5 py-4 font-mono text-xs text-cyan-300">{batch}</td><td className="px-5 py-4">{source}</td><td className="px-5 py-4 font-mono text-xs">{records}</td><td className="px-5 py-4 font-mono text-xs text-emerald-300">{confidence}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-2 rounded-full px-2.5 py-1 text-xs ${status === 'Review' ? 'bg-amber-300/10 text-amber-300' : 'bg-emerald-300/10 text-emerald-300'}`}><span className="size-1.5 rounded-full bg-current" />{status}</span></td><td className="px-5 py-4 text-right"><button aria-label={`Open ${batch}`} className="rounded p-1 text-muted-foreground hover:bg-accent"><ChevronRight className="size-4" /></button></td></tr>)}</tbody></table></div></section>
  <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="panel flex items-center gap-4 p-4"><CircleCheck className="size-5 text-emerald-300" /><div><p className="text-sm font-medium">Optimizer online</p><p className="text-xs text-muted-foreground">All enrichment rules loaded</p></div></div><div className="panel flex items-center gap-4 p-4"><Clock3 className="size-5 text-cyan-300" /><div><p className="text-sm font-medium">Next sync in 12 min</p><p className="text-xs text-muted-foreground">Source systems connected</p></div></div><div className="panel flex items-center gap-4 p-4"><ShieldCheck className="size-5 text-amber-300" /><div><p className="text-sm font-medium">Governance active</p><p className="text-xs text-muted-foreground">Audit trail is recording</p></div></div></div>
</div></AppShell> }
